IF NOT EXISTS 
(
	SELECT name 
	FROM master.dbo.sysdatabases 
	WHERE name = 'BiryukovTestDb'
)
CREATE DATABASE BiryukovTestDb;

USE BiryukovTestDb;

IF NOT EXISTS
(
	SELECT	TABLE_NAME
	FROM	INFORMATION_SCHEMA.COLUMNS
	WHERE	TABLE_NAME = 'Employees'
)
CREATE TABLE Employees 
(	
	EmployeeId INT IDENTITY(1,1) NOT NULL,	
	FirstName NVARCHAR(50) NOT NULL,	
	LastName NVARCHAR(50) NOT NULL,	
	MiddleName NVARCHAR(50) NULL,	
	Email VARCHAR(100) NOT NULL,	
	ContractorCompanyName NVARCHAR(MAX) NOT NULL,
	CONSTRAINT PK_Employees PRIMARY KEY CLUSTERED (EmployeeId)
);

IF NOT EXISTS
(
	SELECT	TABLE_NAME
	FROM	INFORMATION_SCHEMA.COLUMNS
	WHERE	TABLE_NAME = 'Projects'
)
CREATE TABLE Projects 
(	
	ProjectId INT IDENTITY(1,1) NOT NULL,	
	ProjectName NVARCHAR(MAX) NOT NULL,	
	CustomerCompanyName NVARCHAR(MAX) NOT NULL,	
	ManagerId INT NOT NULL,	
	StartDate DATETIME NOT NULL,	
	EndDate DATETIME NOT NULL,	
	[Priority] INT NOT NULL CHECK([Priority] >= 0),	
	Comment NVARCHAR(MAX) NULL, 
	CONSTRAINT PK_Projects PRIMARY KEY CLUSTERED (ProjectId),
	CONSTRAINT FK_ProjectManager FOREIGN KEY(ManagerId) REFERENCES Employees (EmployeeId)
);

IF NOT EXISTS
(
	SELECT	TABLE_NAME
	FROM	INFORMATION_SCHEMA.COLUMNS
	WHERE	TABLE_NAME = 'ProjectsEmployees'
)
CREATE TABLE ProjectsEmployees 
(	
	Id INT IDENTITY(1,1) NOT NULL,	
	ProjectId INT NOT NULL,	
	EmployeeId INT NOT NULL,	
	CONSTRAINT PK_ProjectsEmployees PRIMARY KEY CLUSTERED (Id),
	CONSTRAINT FK_Projects FOREIGN KEY(ProjectId) REFERENCES Projects (ProjectId),
	CONSTRAINT FK_Employees FOREIGN KEY(EmployeeId) REFERENCES Employees (EmployeeId)
);